### PR TITLE
Modifications to be able to apply Weka Model in Unit mode to new text. 

### PR DESCRIPTION
**Pull request by mwunderlich**
As discussed on the mailing list. Also includes some gitignore changes.

### CODE REVIEW

**Comment by reckart** [comment]
A single .gitignore at the repository root suffices. Although Eclipse likes to set up .gitignore files for each module individually, it will in my experience happily obey a well-maintained single one at the root.

**Comment by daxenberger** [comment]
Thanks, Martin. I've cherry-picked all relevant changes from your pull request, and modified the .gitignore commit to only modify the root, as suggested by Richard. Please review; if everything is fine, we can close this pull request.

**Comment by mwunderlich** [comment]
OK, thanks, Johannes. I will able to take a look some time this evening.

**Comment by mwunderlich** [comment]
The entry for .class files in .gitignore should problably have the same path as the groovy files: 
bin/*_/_.class

Other than that, looks ok.

**Comment by reckart** [comment]
Maven projects shouldn't use bin at all. Classes go to target/classes - no matter whether they are Java or Groovy projects.

**Comment by daxenberger** [comment]
Richard is right, we don't need to exclude /bin at all. Done. Closing.

**Pull request closed without merging**
